#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  2 09:50:25 2017

@author: wendywang
"""

import numpy as np

x = np.array(range(5))
y = np.array(range(5,10))
z = np.empty([5,5])

#x = x.reshape(5,5)
#print(x)
#print(y)
#print(np.append(x,y))
#print(z)
print(np.append(z,x))